from fastapi import FastAPI, Depends, HTTPException
from sqlalchemy.orm import Session
from typing import List
import joblib
import pandas as pd
import os

from . import models, schemas, database

# Create tables
models.Base.metadata.create_all(bind=database.engine)

from fastapi.middleware.cors import CORSMiddleware

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Load ML Artifacts
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
MODEL_PATH = os.path.join(BASE_DIR, "models/price_prediction_model.pkl")
ENCODERS_PATH = os.path.join(BASE_DIR, "models/encoders.pkl")

model = None
encoders = None

if os.path.exists(MODEL_PATH) and os.path.exists(ENCODERS_PATH):
    model = joblib.load(MODEL_PATH)
    encoders = joblib.load(ENCODERS_PATH)
    print("ML Model loaded successfully.")
else:
    print("Warning: ML Model not found. Train it first.")

# Dependency
def get_db():
    db = database.SessionLocal()
    try:
        yield db
    finally:
        db.close()

@app.get("/")
def read_root():
    return {"message": "Car Leasing ML API is running"}

@app.post("/predict_price", response_model=schemas.PricePrediction)
def predict_price(car: schemas.CarFeatures):
    if not model or not encoders:
        raise HTTPException(status_code=503, detail="ML Model not available")
    
    # Prepare input data
    input_data = {
        'make': [car.make],
        'model': [car.model],
        'year': [car.year],
        'mileage': [car.mileage],
        'fuel_type': [car.fuel_type],
        'transmission': [car.transmission],
        'engine_size': [car.engine_size]
        # Wait, schematic doesn't have engine_size in CarFeatures but training used it. 
        # I should add engine_size to CarFeatures or use a default.
        # Let's check training script. It used specific engine size.
        # I'll update schema later, for now let's use a dummy or random? 
        # Better: Average engine size is 2.5
    }
    
    # Actually, model expects specific features.
    # 'make', 'model', 'year', 'mileage', 'fuel_type', 'transmission', 'engine_size'
    
    df = pd.DataFrame(input_data)
    
    # Encode categorical features
    try:
        for col in ['make', 'model', 'fuel_type', 'transmission']:
            le = encoders.get(col)
            if le:
                # Handle unseen labels
                # Simple approach: map to unknown or similar. 
                # Scikit-learn LabelEncoder throws error for unseen.
                # For this demo, let's assume valid input or handle error.
                if car.dict()[col] not in le.classes_:
                     raise HTTPException(status_code=400, detail=f"Unknown value for {col}: {car.dict()[col]}")
                df[col] = le.transform(df[col])
    except Exception as e:
         raise HTTPException(status_code=400, detail=str(e))
         
    # Reorder columns to match training
    # The order must match exactly what was used in training.
    # In train_model.py: 
    # X = df.drop('price', axis=1)
    # The columns in df generated by generate_data.py are:
    # make, model, year, mileage, fuel_type, transmission, engine_size, price
    # So X has: make, model, year, mileage, fuel_type, transmission, engine_size
    
    required_cols = ['make', 'model', 'year', 'mileage', 'fuel_type', 'transmission', 'engine_size']
    df = df[required_cols]
    
    prediction = model.predict(df)
    return {"predicted_price": round(prediction[0], 2), "currency": "USD"}

# CRUD for Cars
@app.post("/cars/", response_model=schemas.Car)
def create_car(car: schemas.CarCreate, db: Session = Depends(get_db)):
    db_car = models.Car(**car.dict())
    db.add(db_car)
    db.commit()
    db.refresh(db_car)
    return db_car

@app.get("/cars/", response_model=List[schemas.Car])
def read_cars(skip: int = 0, limit: int = 100, db: Session = Depends(get_db)):
    cars = db.query(models.Car).offset(skip).limit(limit).all()
    return cars
